runtime: python37
instance_class: F4_1G

includes:
  - env_variables.yaml

handlers:
- url: /static
  static_dir: static

beta_settings:
  cloud_sql_instances: pip-project-survey:northamerica-northeast1:testdb
